export default {
  links: [
    { text: "Home", path: "/", selected: true },
    { text: "Pokédex", path: "/pokedex" },
    { text: "Legendaries", path: "/pokedex/legendaries" },
    { text: "Documentation", path: "/documentation" },
  ],
  filters: {
    types: [
      { text: "Type", value: "DEFAULT", disabled: true },
      { text: "Bug", value: "bug" },
      { text: "Dark", value: "dark" },
      { text: "Dragon", value: "dragon" },
      { text: "Electric", value: "electric" },
      { text: "Fairy", value: "fairy" },
      { text: "Fighting", value: "fighting" },
      { text: "Fire", value: "fire" },
      { text: "Flying", value: "flying" },
      { text: "Ghost", value: "ghost" },
      { text: "Grass", value: "grass" },
      { text: "Ground", value: "ground" },
      { text: "Ice", value: "ice" },
      { text: "Normal", value: "normal" },
      { text: "Poison", value: "poison" },
      { text: "Psychic", value: "psychic" },
      { text: "Rock", value: "rock" },
      { text: "Steel", value: "steel" },
      { text: "Water", value: "water" },
    ],
    attack: [
      { text: "Attack", value: "DEFAULT", disabled: true },
      { text: "Lowest first", value: "lowest" },
      { text: "Highest first", value: "highest" },
    ],
    experience: [
      { text: "Experience", value: "DEFAULT", disabled: true },
      { text: "Lowest first", value: "lowest" },
      { text: "Highest first", value: "highest" },
    ],
  },
  cards: [
    {
      id: 869,
      name: "Alcremie",
      attack: 60,
      defense: 75,
      experience: 173,
      types: ["Fairy"],
    },
    {
      id: 144,
      name: "Articuno",
      attack: 85,
      defense: 100,
      experience: 261,
      types: ["Ice", "Flying"],
    },
    {
      id: 182,
      name: "Bellossom",
      attack: 80,
      defense: 95,
      experience: 221,
      types: ["Grass"],
    },
    {
      id: 152,
      name: "Chikorita",
      attack: 49,
      defense: 65,
      experience: 64,
      types: ["Grass"],
    },
    {
      id: 852,
      name: "Clobbopus",
      attack: 68,
      defense: 60,
      experience: 62,
      types: ["Fighting"],
    },
    {
      id: 415,
      name: "Combee",
      attack: 30,
      defense: 42,
      experience: 49,
      types: ["Bug", "Flying"],
    },
    {
      id: 823,
      name: "Corviknight",
      attack: 87,
      defense: 105,
      experience: 248,
      types: ["Flying", "Steel"],
    },
    {
      id: 483,
      name: "Dialga",
      attack: 120,
      defense: 120,
      experience: 306,
      types: ["Steel", "Dragon"],
    },
    {
      id: 196,
      name: "Espeon",
      attack: 65,
      defense: 60,
      experience: 184,
      types: ["Psychic"],
    },
    {
      id: 136,
      name: "Flareon",
      attack: 130,
      defense: 60,
      experience: 184,
      types: ["Fire"],
    },
    {
      id: 873,
      name: "Frosmoth",
      attack: 65,
      defense: 60,
      experience: 166,
      types: ["Ice", "Bug"],
    },
    {
      id: 162,
      name: "Furret",
      attack: 76,
      defense: 64,
      experience: 145,
      types: ["Normal"],
    },
    {
      id: 94,
      name: "Gengar",
      attack: 65,
      defense: 60,
      experience: 225,
      types: ["Ghost", "Poison"],
    },
    {
      id: 472,
      name: "Gliscor",
      attack: 95,
      defense: 125,
      experience: 179,
      types: ["Ground", "Flying"],
    },
    {
      id: 706,
      name: "Goodra",
      attack: 100,
      defense: 70,
      experience: 270,
      types: ["Dragon"],
    },
    {
      id: 385,
      name: "Jirachi",
      attack: 100,
      defense: 100,
      experience: 270,
      types: ["Steel", "Psychic"],
    },
    {
      id: 595,
      name: "Joltik",
      attack: 47,
      defense: 50,
      experience: 64,
      types: ["Bug", "Electric"],
    },
    {
      id: 404,
      name: "Luxio",
      attack: 85,
      defense: 49,
      experience: 127,
      types: ["Electric"],
    },
    {
      id: 66,
      name: "Machop",
      attack: 80,
      defense: 50,
      experience: 61,
      types: ["Fighting"],
    },
    {
      id: 262,
      name: "Mightyena",
      attack: 90,
      defense: 70,
      experience: 147,
      types: ["Dark"],
    },
    {
      id: 350,
      name: "Milotic",
      attack: 60,
      defense: 79,
      experience: 189,
      types: ["Water"],
    },
    {
      id: 429,
      name: "Mismagius",
      attack: 60,
      defense: 60,
      experience: 173,
      types: ["Ghost"],
    },
    {
      id: 32,
      name: "Nidoran♂",
      attack: 57,
      defense: 40,
      experience: 55,
      types: ["Poison"],
    },
    {
      id: 793,
      name: "Nihilego",
      attack: 53,
      defense: 47,
      experience: 257,
      types: ["Rock", "Poison"],
    },
    {
      id: 862,
      name: "Obstagoon",
      attack: 90,
      defense: 101,
      experience: 260,
      types: ["Dark", "Normal"],
    },
    {
      id: 138,
      name: "Omanyte",
      attack: 40,
      defense: 100,
      experience: 71,
      types: ["Rock", "Water"],
    },
    {
      id: 53,
      name: "Persian",
      attack: 70,
      defense: 60,
      experience: 154,
      types: ["Normal"],
    },
    {
      id: 172,
      name: "Pichu",
      attack: 40,
      defense: 15,
      experience: 41,
      types: ["Electric"],
    },
    {
      id: 393,
      name: "Piplup",
      attack: 51,
      defense: 53,
      experience: 63,
      types: ["Water"],
    },
    {
      id: 821,
      name: "Rookidee",
      attack: 47,
      defense: 35,
      experience: 49,
      types: ["Flying"],
    },
    {
      id: 373,
      name: "Salamence",
      attack: 135,
      defense: 80,
      experience: 270,
      types: ["Dragon", "Flying"],
    },
    {
      id: 28,
      name: "Sandslash",
      attack: 100,
      defense: 110,
      experience: 158,
      types: ["Ground"],
    },
    {
      id: 218,
      name: "Slugma",
      attack: 40,
      defense: 40,
      experience: 50,
      types: ["Fire"],
    },
    {
      id: 791,
      name: "Solgaleo",
      attack: 137,
      defense: 107,
      experience: 306,
      types: ["Psychic", "Steel"],
    },
    {
      id: 317,
      name: "Swalot",
      attack: 73,
      defense: 83,
      experience: 163,
      types: ["Poison"],
    },
    {
      id: 888,
      name: "Zacian",
      attack: 170,
      defense: 115,
      experience: 360,
      types: ["Fairy"],
    },
  ],
};
